package stitch.engine.step;

import stitch.domain.ProjectContext;
import stitch.util.Logger;

import java.nio.file.*;
import java.util.*;
import java.util.spi.ToolProvider;

public class PackageJarStep implements BuildStep {
    @Override
    public void execute(ProjectContext context) {
        ToolProvider jar = ToolProvider.findFirst("jar").orElseThrow(() -> new RuntimeException("jar tool not found"));

        String projectName = context.config().projectName();
        Path outputJar = Path.of("target").resolve(projectName + ".jar");
        Path classesDir = Path.of("target/classes").resolve(projectName).resolve(context.module().name().value());

        List<String> args = new ArrayList<>(List.of("--create", "--file", outputJar.toString()));
        context.config().mainClass().ifPresent(main -> {
            args.add("--main-class");
            args.add(main);
        });
        args.addAll(List.of("-C", classesDir.toString(), "."));

        if (jar.run(System.out, System.err, args.toArray(String[]::new)) != 0) {
            throw new RuntimeException("Failed to create JAR for " + projectName);
        }
        Logger.info("📦 [" + projectName + "] Created JAR: " + outputJar);

        // Copy dependencies to target/lib for easier runtime execution
        if (!context.resolvedDependencies().isEmpty()) {
            Path libDir = Path.of("target", "lib");
            try {
                Files.createDirectories(libDir);
                for (Path dep : context.resolvedDependencies()) {
                    Files.copy(dep, libDir.resolve(dep.getFileName()), StandardCopyOption.REPLACE_EXISTING);
                }
                Logger.info("📚 [" + projectName + "] Copied dependencies to: " + libDir);

                context.config().mainClass().ifPresent(main ->
                    Logger.info("🚀 Run with: java -p " + libDir + ":" + outputJar + " -m " + context.module().name().value() + "/" + main)
                );
            } catch (Exception e) {
                Logger.error("⚠️ Failed to copy dependencies to lib folder: " + e.getMessage());
            }
        }

        // Generate the executable launcher script if a main class exists
        context.config().mainClass().ifPresent(main -> {
            try {
                Path launcher = Path.of("target", projectName);
                // Ensure lib exists even if empty, so the script doesn't fail
                if (context.resolvedDependencies().isEmpty()) {
                     Files.createDirectories(Path.of("target", "lib"));
                }

                String moduleName = context.module().name().value();

                String script = """
                    #!/bin/sh
                    # Auto-generated by Stitch Build System
                    
                    # Resolve the directory where this script lives
                    DIR="$(cd "$(dirname "$0")" && pwd)"
                    
                    # Execute the modular JAR
                    exec java -p "$DIR/lib:$DIR/%s.jar" -m %s/%s "$@"
                    """.formatted(projectName, moduleName, main);

                Files.writeString(launcher, script);
                launcher.toFile().setExecutable(true);

                Logger.info("🚀 Run your app effortlessly with: ./" + launcher);
            } catch (Exception e) {
                Logger.error("⚠️ Failed to create launcher script: " + e.getMessage());
            }
        });
    }
}
